import type { NextConfig } from "next";
import imageSizes from "./lib/image-sizes.json";

const nextConfig: NextConfig = {
  output: 'export',          // writes to ./out
  images: {                  // WebP variants pre-generated by scripts/images/optimize.mjs
    loader: 'custom',
    loaderFile: './lib/image-loader.ts',
    deviceSizes: imageSizes.deviceSizes,
    imageSizes: imageSizes.imageSizes,
  },
  trailingSlash: true,       // makes /docs/page/ resolve cleanly
  devIndicators: false,
}

export default nextConfig;
