// next/image loader for the static export: maps /images/<name>.png at a width to the
// WebP variant generated by scripts/images/optimize.mjs (public/images/_v/<name>-<width>.webp).
export default function imageLoader({ src, width }: { src: string; width: number; quality?: number }) {
  const match = /^\/images\/([^/]+)\.(png|jpe?g)$/i.exec(src);
  if (!match) return src;
  return `/images/_v/${match[1]}-${width}.webp`;
}
